language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
script: php -f ./loader/loader.php
notifications:
  email: false
  irc:
    skip_join: false
    on_success: never
    on_failure: always
    channels:
      - "irc.gamesurge.net#UC"
    template:
      - "%{repository}#%{build_number} (%{commit} by %{author}): %{message}"
      - "Build details: %{build_url}"
